-- Sag page events (2026-09-07): sag_measured_saved {bike_id, version_id,
-- riding_mm, static_mm, in_range}, sag_recheck_shown {bike_id,
-- ride_days_since, last_measured_at}, sag_recheck_completed {bike_id}.
-- STAGED, NOT PUSHED.
--
-- Carries the FULL list: the 20260907170000 set (95) + 3 = 98. Never add
-- another re-add without carrying all 98.

alter table public.usage_events
  drop constraint usage_events_event_type_check;

alter table public.usage_events
  add constraint usage_events_event_type_check
  check (event_type in (
    'ai_tune_generated',
    'session_saved',
    'session_deleted',
    'bike_created',
    'bike_updated',
    'ai_tune_generated_zero',
    'version_created',
    'feedback_submitted',
    'outcome_recorded',
    'chip_toggled',
    'where_selected',
    'protect_toggled',
    'conditions_selected',
    'heard_card_shown',
    'checkin_shown',
    'checkin_answered',
    'checkin_dismissed',
    'preride_shown',
    'preride_history_tapped',
    'preride_copied',
    'history_opened',
    'history_version_expanded',
    'restore_started',
    'restore_confirmed',
    'history_gate_hit',
    'setup_shared',
    'preset_applied',
    'sign_in',
    'sign_up',
    'onboarding_intro_completed',
    'onboarding_bike_added',
    'onboarding_tune_generated',
    'onboarding_locked_results_viewed',
    'onboarding_unlock_clicked',
    'onboarding_signup_started',
    'onboarding_signup_completed',
    'onboarding_paywall_shown',
    'onboarding_paywall_dismissed',
    'onboarding_trial_started',
    'onboarding_completed',
    'decliner_home_landed',
    'decliner_banner_tapped',
    'decliner_converted',
    'trial_countdown_shown',
    'trial_countdown_cta_tapped',
    'trial_value_card_shown',
    'trial_value_card_dismissed',
    'winback_screen_shown',
    'winback_cta_tapped',
    'bike_search_no_result',
    'oauth_started',
    'oauth_failed',
    'loop_preview_shown',
    'hook_ride_armed',
    'quiz_step_viewed',
    'quiz_step_answered',
    'quiz_abandoned',
    'quiz_gate_viewed',
    'quiz_signin_method_chosen',
    'quiz_reveal_viewed',
    'quiz_freetext_expanded',
    'quiz_freetext_filled',
    'paywall_shown',
    'paywall_dismissed',
    'paywall_purchased',
    'home_module_viewed',
    'goal_set',
    'next_ride_set',
    'sheet_row_expanded',
    'story_opened',
    'run_setup_switched',
    'ride_day_started',
    'moto_logged',
    'adjust_shown',
    'adjust_confirmed',
    'retune_applied',
    'ride_day_ended',
    'baseline_saved',
    'session_resumed',
    'session_autoclosed',
    'track_created',
    'track_match_confirmed',
    'sync_queue_flushed',
    'pro_gate_shown',
    'pro_gate_alternative',
    'trial_started',
    'trial_ended',
    'downgraded',
    'gate_shown',
    'gate_dismissed',
    'gate_converted',
    'pricing_page_viewed',
    'lifetime_offered',
    'qualified_trial',
    'free_refine_used',
    'sag_measured_saved',
    'sag_recheck_shown',
    'sag_recheck_completed'
  ));
